# Generated by Django 3.2 on 2022-12-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='飲み会名')),
                ('date', models.DateField(verbose_name='予約日')),
                ('time', models.TimeField(verbose_name='時間')),
                ('restaurant', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(max_length=500, verbose_name='場所')),
                ('url', models.URLField(verbose_name='店舗リンク')),
                ('subscriber', models.CharField(max_length=100, verbose_name='予約者名')),
                ('fee', models.PositiveIntegerField(verbose_name='会費')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('create_dt', models.DateTimeField(verbose_name='作成日時')),
                ('mod_dt', models.DateTimeField(verbose_name='編集日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
