# Generated by Django 3.2 on 2023-01-03 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0003_notjoinforparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinforparty',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='飲み会名'),
        ),
        migrations.AlterField(
            model_name='joinforparty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
        migrations.AlterField(
            model_name='notjoinforparty',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='飲み会名'),
        ),
        migrations.AlterField(
            model_name='notjoinforparty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='欠席者'),
        ),
        migrations.CreateModel(
            name='TbdForParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='飲み会名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='未定者')),
            ],
        ),
    ]
