# Generated by Django 3.2 on 2023-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_alter_party_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.CharField(max_length=500, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='party',
            name='comment',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='party',
            name='mod_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='編集日時'),
        ),
    ]
